import { writeFileSync } from "node:fs";
import { resolve } from "node:path";

const esc = (s) => String(s).replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;");
const rows = (items) => items.map(r => `<tr>${r.map(c => `<td>${c}</td>`).join("")}</tr>`).join("");
const table = (heads, items, cls="") => `<table class="${cls}"><thead><tr>${heads.map(h=>`<th>${h}</th>`).join("")}</tr></thead><tbody>${rows(items)}</tbody></table>`;
const box = (title, body, kind="note") => `<div class="box ${kind}"><b>${title}</b><div>${body}</div></div>`;
const code = (s) => `<pre><code>${esc(s)}</code></pre>`;
const pages=[];
const page=(title,html,kicker="ROOTLORE • INTERVIEW FIELD GUIDE")=>pages.push(`<section class="page"><header><span>${kicker}</span><span>${pages.length+1}</span></header><h1>${title}</h1>${html}<footer>Source-verified at commit 7a9cb1c • 04 Sep 2026</footer></section>`);

page("RootLore", `<div class="cover"><div class="eyebrow">2-DAY TECHNICAL INTERVIEW PREP</div><h2>Evidence-grounded GitHub issue intelligence</h2><p class="lede">A source-verified guide for fresher SDE, backend, full-stack and graduate engineer interviews.</p><div class="flow big"><span>Retrieve</span><i>→</i><span>Rank</span><i>→</i><span>Generate</span><i>→</i><span>Validate</span></div>${box("Evidence standard", "Current source code is authoritative. README claims were checked against code. Tests, evaluation, and production build were run locally.","good")}${box("Resume caveat", "No resume file was present in the supplied attachment directory or repository. This guide therefore does not claim how RootLore is worded on your resume. Compare the recommended pitch with your resume before the interview.","warn")}<div class="facts"><b>44/44</b><span>tests passing</span><b>4/4</b><span>toy retrieval cases</span><b>3</b><span>API routes</span><b>4</b><span>outcomes</span></div></div>`);

page("1. Project foundation", `<h2>Simple first</h2><p>GitHub answers are often scattered across old issues, maintainer comments, docs and releases. RootLore collects a small relevant set, asks an LLM to reason only over it, then checks the model’s citations and risky claims before showing an answer. If it cannot support a fix, it improves the report and asks for missing diagnostics.</p><h2>Interview-ready definition</h2><p>RootLore is a multi-interface retrieval-augmented issue assistant. A React/Vite web app or Chrome MV3 extension calls an Express API. The API retrieves bounded GitHub evidence, ranks it lexically, sends selected context to Groq’s <code>openai/gpt-oss-20b</code> under a strict JSON Schema, and deterministically validates the generated result.</p>${table(["Question","Answer"],[["Problem","Project-specific knowledge is fragmented; generic LLMs can hallucinate; issue reports are incomplete."],["Users","Developers, issue reporters and maintainers working with a GitHub repository."],["Use cases","Find related issues; suggest evidence-backed remediation; improve a report; identify a possible duplicate."],["Interesting part","The LLM is not trusted as the final authority: evidence selection and post-generation checks are code-enforced."],["Limitations","Lexical—not semantic—retrieval; bounded repo view; process-local caches; no auth/history sync; tiny evaluation set."],["Future","Embeddings/hybrid search, shared cache, authentication, broader evaluations, Discussions/PR-diff indexing."]])}${box("DO NOT SAY THIS", "“It scans the whole repository” or “it guarantees the fix.” The code reads bounded docs and only explicitly named source files; inferred/tentative actions require review.","bad")}`);

// Pitch ladder is consolidated into the final revision page to keep the guide within 30 A4 pages.

const tech=[
["JavaScript + ES modules","One language/runtime module system","Backend, web, extension; <code>type: module</code>","TypeScript","Fast iteration; fewer compile-time checks"],
["Node.js 20+","Server JS runtime","Async network-heavy API","Java/.NET","Simple shared language; CPU work can block event loop"],
["Express 5.1","HTTP framework","Routes, JSON, middleware","Fastify/Nest","Small; fewer built-in conventions"],
["React 19 + Vite 8","UI + build tool","SPA form/results/history","Next/Vue","Fast dev/build; client app needs API"],
["Chrome MV3","Extension platform","Reads/inserts GitHub issue content","Userscript","Integrated UX; permissions/DOM fragility"],
["GitHub REST API","Repository HTTP API","Issues/comments/timeline/releases/tree/content","GraphQL","Simple endpoints; several calls/rate limits"],
["Groq + gpt-oss-20b","Hosted LLM inference","Structured reasoning over evidence","OpenAI/local model","Speed/JSON schema; provider dependency"],
["JSON Schema","Output contract","Strict response shape","Free text/Zod","Predictable parsing; schema failure possible"],
["cors 2.8","Browser origin policy middleware","Allow configured web origins and extensions","Proxy-only","Simple; extension origin rule is broad"],
["dotenv 16.6","Loads environment secrets","GitHub/Groq keys, port, CORS","Secret manager","Good locally; production needs managed secrets"],
["In-memory Map caches","TTL + dedup","GitHub/Groq response reuse","Redis","No infrastructure; not shared/durable"],
["Node test runner","Built-in tests","44 unit/integration tests","Vitest/Jest","Zero extra runner; simpler ecosystem"],
];
page("2. Complete tech stack", table(["Technology","What / where","Why","Alternative","Trade-off"],tech,"dense")+box("Explicitly NOT used", "No MongoDB, PostgreSQL, Redis, JWT, server sessions, embeddings, vector database, LangChain or ChromaDB appear in dependencies or source. Browser history uses <code>localStorage</code>; extension settings/result use Chrome storage.","note"));

page("3. Architecture", `<div class="diagram">USER<br><b>React/Vite web app OR Chrome MV3 extension</b><br>↓ POST JSON<br><b>Express route + validation + per-IP limiter</b><br>↓<br><b>GitHub retrieval</b> → local lexical ranking → bounded evidence<br>↓<br><b>Groq structured generation</b><br>↓<br><b>parse + deterministic validation</b><br>↓ JSON<br><b>outcome UI + browser-local history</b></div><h2>Where logic lives</h2>${table(["Layer","Responsibility"],[["<code>src/app.js</code>","CORS, JSON parsing, health route, router, 404 and error middleware."],["<code>routes/repositories.js</code>","Request orchestration, validation, optional-evidence degradation and response assembly."],["<code>services/github.js</code>","GitHub fetch, normalization, TTL cache, ETag, failures and bounded docs/files."],["<code>services/analysis.js</code>","Token/error/numeric matching, ranking, path extraction and command correction."],["<code>services/groq.js</code>","Schema/prompt, provider call/cache, parsing, sanitization, outcome decision."],["<code>web/src/App.jsx</code>","Repository parsing, submit, results, history and quality display."],["<code>extension/*</code>","GitHub DOM extraction/insertion, popup flow, settings and API call."]])}`);

page("4. End-to-end analysis flow", `<ol class="steps"><li>User enters a GitHub URL, title and description; the web UI parses <code>owner/repository</code>. Extension can also send <code>issueNumber</code>.</li><li><code>POST /api/repositories/:owner/:repository/analyze</code>; params come from URL, body from parsed JSON.</li><li>Limiter counts the client IP; validation checks name regex, strings, non-empty text, title ≤200, description ≤10,000.</li><li>Fetch recent issues (≤100), optional older search (≤20), and optional current issue; remove duplicates by issue number.</li><li>Extract ≤3 explicit file paths and rank issues; current issue is forced in, total evidence issues ≤3.</li><li><code>Promise.all</code> concurrently enriches selected issues plus releases, docs and named files. Optional failures become <code>[]</code>.</li><li>Rank docs/source; combine command corrections + files + docs, deduplicate, slice to ≤4 passages.</li><li>Groq receives bounded evidence and strict schema. Provider JSON is parsed, citations/claims are validated, and an outcome is chosen.</li><li>API returns evidence, optimization counts, model metadata and analysis; UI renders and stores last 10 analyses locally.</li></ol>${box("Async interview point", "<code>await</code> pauses this async function without blocking Node’s process. <code>Promise.all</code> overlaps independent I/O. Removing <code>await</code> would pass unresolved Promises or return too early; one rejection rejects the group, but optional calls are wrapped to resolve as empty arrays.","good")}`);

page("5. RAG from zero", `<h2>Three verbs</h2><div class="three"><div><b>Retrieve</b><p>Find relevant repository evidence.</p></div><div><b>Augment</b><p>Add that evidence to the model prompt.</p></div><div><b>Generate</b><p>Create a structured answer grounded in it.</p></div></div><p><b>Grounding</b> ties claims to supplied evidence. <b>Hallucination</b> is unsupported generated content. A <b>context window</b> is the model’s limited input capacity. Retrieval quality determines whether useful evidence reaches it.</p><h2>Why RootLore qualifies</h2><p>It retrieves issues, comments, timelines, releases, documentation and explicit files before generation, selects relevant evidence locally, and injects it into the Groq request. It is RAG without vectors.</p><h2>Actual retrieval type: lexical</h2><p>Words are lowercased, tokenized (≥3 chars), stop words removed, and simple plural endings normalized. Issue score weights title ×3, labels ×2, body ×1 and exact errors ×4; score threshold is 15%. Documents score shared terms plus 3 for numbers within 5%.</p>${box("Why no embeddings?", "For an MVP, lexical scoring was explainable, deterministic, dependency-light and easy to regression-test. The trade-off is missing semantic matches with different vocabulary. Add embeddings later by chunking docs/issues, storing vectors with metadata, retrieving top-k semantic results, then combining normalized lexical and vector scores—while retaining exact-quote validation.","good")}`);

page("6. GitHub evidence retrieval", table(["Evidence","Actual bound / value","Purpose","Failure"],[["Recent issues","1 page × 100; PRs filtered","Broad current history","Core failure aborts with GitHub status"],["Older search","≤20; ≤2 signature/title terms","Find matches outside recent window","Optional → empty"],["Current issue","Exact issue endpoint","Never lose viewed discussion","Optional → null"],["Comments","≤20 for each of ≤3 issues","Resolution/user evidence","Optional → empty"],["Timeline","≤100 raw; retain close/reopen/commit/linked PR","Identify closer and links","Optional → empty"],["Releases","≤10 fetched; ≤3 sent, body ≤400 chars","Connect fixes to versions","Optional → empty"],["Docs","≤20 files, each ≤100KB, total ≤750KB","Instructions/config/troubleshooting","Optional → empty"],["Explicit source","≤3 paths; file ≤150KB","Bounded code/data inference","Missing/invalid → empty"],["Prompt passages","≤4; each ≤600 chars sent","Keep context focused","Continue with remaining evidence"]],"dense")+box("Why bounded?", "An entire repository increases GitHub calls, latency, token cost, context noise and prompt-injection surface. Bounded retrieval also makes behavior testable and keeps provider usage predictable.","note"));

page("7. Groq and structured generation", `<p><b>Provider/model:</b> <code>POST https://api.groq.com/openai/v1/chat/completions</code>, model <code>openai/gpt-oss-20b</code>, temperature 0.2, max completion 2,200 tokens, timeout 30s.</p><p><b>Input bounds:</b> current issue body 1,000 chars/last 6 comments ×400; other bodies 600/last 3 comments ×300; last 3 timeline events; 3 releases ×400; 4 passages ×600; submitted description sent at ≤5,000 although route accepts ≤10,000.</p><p><b>Schema:</b> summary, improved title/report, questions, duplicate, suggested solution, confidence, issue claims and documentation claims. <code>strict: true</code> reduces parsing ambiguity; local shape checks remain.</p><p><b>Failures:</b> network/timeout →503; non-JSON or invalid shape →502; provider HTTP status preserved. A valid JSON object inside <code>error.failed_generation</code> can be recovered with conservative defaults, then fully validated.</p><p><b>Cache:</b> SHA-256 of report + evidence versions, 24h TTL, ≤250 entries, concurrent identical requests share one Promise.</p>${box("Could it work without AI?", "Partly. Ranking, duplicate candidates, deterministic command correction, quality scoring and issue templates can work without AI. The LLM adds synthesis, cautious inference, follow-up questions and natural rewriting. A non-AI fallback would be less flexible but more predictable.","good")}`);

page("8. Hallucination controls", `<ul><li><b>Evidence-only prompt:</b> repository text is declared untrusted and cannot override system instructions.</li><li><b>Allow-list:</b> issue numbers and document paths must exist in the supplied evidence.</li><li><b>Exact quote:</b> normalized quote length ≥12 and must be a substring of matching evidence.</li><li><b>Duplicate:</b> needs a validated claim marked <code>duplicate</code>; current issue cannot match itself.</li><li><b>Closure:</b> closed + not <code>not_planned</code> + final closer’s comment says fixed/resolved/worked; closure alone is insufficient.</li><li><b>Versions:</b> suggested solution cannot introduce version tokens absent from report/evidence.</li><li><b>Risk:</b> low-confidence destructive/state-changing verbs are blocked without solution evidence.</li><li><b>Improved report:</b> invented environment, reproduction steps and errors are removed; retrieved facts cannot impersonate reporter observations.</li><li><b>Context vs decision:</b> summary-only claims are relabeled as similarity and capped at two; they do not verify cause.</li></ul><div class="flow"><span>Unsupported claim</span><i>→</i><span>validator rejects quote/version/action</span><i>→</i><span>downgrade/remove</span><i>→</i><span>safe outcome</span></div>${box("Why prompt rules are insufficient", "Models can misunderstand, ignore instructions, or return malformed/crafted content. Deterministic checks are a second, testable boundary. They reduce—not eliminate—hallucination and prompt-injection risk.","warn")}`);

page("Outcome decision matrix", table(["Outcome","Code condition","How to explain"],[["<code>verified_solution</code>","Validated solution claim from issue/docs or deterministic correction/closer confirmation","Repository evidence directly supports the action."],["<code>inferred_solution</code>","No direct solution; grounding exists; medium/high confidence; safe solution text","Bounded AI inference, explicitly review-required."],["<code>possible_remediation</code>","Safe generated direction remains but is not verified/inferred","Plausible and unverified; low confidence cannot be destructive."],["<code>structured_issue</code>","No responsible remediation survives","Collect diagnostics / send improved report."]])+code(`const possibleDuplicate =
  analysis.possibleDuplicate !== currentIssueNumber &&
  allowedNumbers.has(analysis.possibleDuplicate) &&
  evidenceClaims.some(item =>
    item.issueNumber === analysis.possibleDuplicate &&
    item.supports.includes("duplicate"))
    ? analysis.possibleDuplicate : null;`)+box("Interview warning", "A validated exact quote proves the quote exists, not that the repository’s statement is universally correct. The prompt explicitly treats repository text as evidence of intent, not automatic technical truth.","warn"));

page("9. API interview table", table(["Method + route","Purpose / input","Validation + limit","Response / failures"],[["GET <code>/health</code>","Liveness; no params/body","No analysis limiter","200 <code>{status:'ok'}</code>"],["GET <code>/api/repositories/:owner/:repository/issues</code>","Normalized issues; URL params","Name regex; no custom rate limit","200; 400 invalid; GitHub status or 500"],["POST <code>/api/repositories/:owner/:repository/analyze</code>","Body: title, description, optional integer issueNumber","Regex, types, nonempty, 200/10k limits; 10/IP/10min","200 analysis; 400; 429; upstream 4xx/5xx; 502/503"]],"dense")+`<h2>Status reasoning</h2><p><b>POST</b> carries a report and triggers a composed analysis; <b>GET</b> reads a resource. <b>400</b> means client input is invalid. <b>404</b> is used by unknown local routes or can pass from GitHub. <b>429</b> protects quota. <b>500</b> is unexpected server failure; <b>502</b> invalid provider output; <b>503</b> missing Groq key, timeout or unreachable upstream.</p>${box("How to secure further", "Add authentication/authorization, stricter extension-origin allow-list, request body size at parser level, proxy trust configuration, distributed rate limiting, audit logs, secret manager, outbound allow-list, prompt-injection red teaming and abuse monitoring.","good")}`);

page("10. Caching and performance", table(["Mechanism","Actual behavior","Limit"],[["Fresh cache","Return Map data within TTL","Process-local"],["Stale + ETag","Send <code>If-None-Match</code>; 304 refreshes timestamp","Depends on GitHub ETag"],["Failure cache","Remember error 60s","Short recovery delay"],["In-flight dedup","Same URL/analysis shares one Promise","Only one process"],["GitHub cache","Issues 15m; supporting 6h; docs/source 24h","≤500 entries; oldest insertion removed"],["Groq cache","Analysis 24h","≤250 entries; oldest insertion removed"],["Parallel I/O","Nested <code>Promise.all</code>","One unwrapped rejection fails group"],["Timeouts","GitHub 15s; Groq 30s; extension 45s","Web fetch has no explicit timeout"],["Rate limit","10 analyses/IP/10m","Map records are not pruned proactively"]])+box("Multiple backend instances", "Each instance has separate cache and limiter state, so hit rate drops, duplicate upstream calls occur, and a client can receive more total allowance. Use Redis (or another shared TTL store) for cached data, locks/request coalescing and atomic distributed counters.","good")+box("Stale cache", "Expired entries are not immediately deleted. A later request revalidates with ETag; if unchanged, GitHub returns 304 and the cached data becomes fresh.","note"));

page("11. Security review", table(["Risk","Current protection","Gap / improvement"],[["Secret exposure","Keys only in backend env; <code>.env</code> ignored","Use cloud secret manager, rotation, least-scope token"],["CORS","Configured origins; any <code>chrome-extension://</code> allowed","Allow-list exact extension ID; CORS is not authentication"],["Abuse/DoS","Per-IP analysis limiter, bounds, timeouts, caches","Distributed limiter, parser body limit, quotas, proxy IP config"],["Input injection","Regex, type, length checks; repo text called untrusted","More prompt-injection tests; isolate/label data"],["Data leakage","Bounded evidence; keys not sent to client","Private repo content reaches Groq; disclose/consent/redact"],["Extension permissions","activeTab/storage/scripting; limited host permissions","Audit DOM injection and production host changes"],["HTML/script injection","React escapes strings by default","Keep URLs constrained; CSP/headers"],["Private repos","Token permissions govern access","No per-user auth; server token may over-broaden access"]],"dense")+box("Important nuance", "The manifest permits localhost and <code>https://*.onrender.com/*</code>. Content script matches GitHub issue URLs. The API’s extension CORS branch accepts every extension origin; rate limiting and validation still apply but do not establish identity.","warn"));

page("12. Failure and edge cases", table(["Case","Actual result"],[["GitHub core fetch fails / limit","Analyze route returns upstream status; network/timeout is 503; rate-limit message recognized."],["Optional search/comments/timeline/releases/docs/file fails","Converted to empty evidence; analysis continues."],["Groq absent/unreachable/timeout","503. Invalid structured response is 502; provider status otherwise preserved."],["Invalid repo syntax","400 before GitHub. Valid-looking nonexistent/private inaccessible repo passes GitHub error (commonly 404)."],["Empty/non-string/too long report","400. Title max 200; description max 10,000."],["Current issue retrieved as candidate","Forced into evidence but forbidden as its own duplicate."],["No/weak evidence","Confidence becomes low; unsafe actions removed; structured issue or cautious remediation."],["Huge docs","Only eligible ≤100KB files, ≤20 and ≤750KB; passages bounded."],["Missing referenced file","Optional empty; no repository scan fallback."],["Duplicate request","GitHub and Groq in-flight/cache reuse when keys match."],["Frontend cannot reach API","UI catches and displays fetch error; extension times out at 45s."],["CORS rejected","Error middleware returns 403 JSON."]],"dense"));

page("13. Testing and evaluation", `<div class="facts"><b>44/44</b><span>node tests</span><b>4/4</b><span>retrieval fixtures</span><b>100%</b><span>top-1 on 4 cases only</span><b>PASS</b><span>Vite build</span></div>${table(["Area","What is tested"],[["Analysis (8)","Lexical/error ranking, stop words, document/numeric ranking, paths, source chunks, command typo."],["GitHub (2)","Search-term selection."],["Groq/validation (21)","Citations, reports, closures, outcomes, versions, unsafe actions, sanitation, parse/recovery."],["Quality (6)","Logs, reproduction wording and placeholders."],["Rate limit (1)","Allowance rejection."],["Route/integration (6)","Mocked pipeline, current issue, 502, cache reuse, 400 and CORS."]])}<h2>Commands</h2><p><code>npm test</code> runs Node’s test runner. <code>npm run evaluate</code> measures top-1 on four labeled synthetic fixtures. <code>npm run check</code> chains tests, evaluation and the web production build.</p>${box("DO NOT SAY THIS", "“The model is 100% accurate.” The 4/4 figure tests only the deterministic issue ranker on four easy fixtures. It does not measure generation, real repositories, no-match behavior, citation precision or production latency.","bad")}<p><b>Better evaluation:</b> 5–10 repositories, 10–20 queries each, second-person labels, synonyms/ambiguity/no-match/older cases; report Precision@1, Recall@5, MRR, no-match metrics, groundedness, p50/p95 latency and API/token cost.</p>`);

const debug=[
["Similar issue ranked too low","Log tokens and score components","Synonyms share no terms","Add hybrid embeddings or domain normalization","Measure retrieval separately"],
["Closed issue shown as a fix","Inspect stateReason, timeline closer and comments","Closure was stale/not_planned or unconfirmed","Require closer-confirmed resolution phrase","State ≠ resolution"],
["Invented error entered improved report","Compare generated fields with submitted report","Model copied retrieved issue data","Sanitize errors/steps/environment against submission","Generated rewriting needs provenance"],
["Burst causes GitHub/Groq quota pressure","Count repeated URLs/cache keys","Concurrent identical calls duplicated","Share in-flight Promise + cache failures briefly","Coalescing matters under load"],
["Valid-looking Groq response breaks UI","Capture raw provider envelope","Malformed/missing structured fields","Strict schema + local parser + controlled 502/recovery","Never trust provider shape"],
];
page("14. Debugging stories", `<p class="small"><b>All five are hypothetical practice scenarios grounded in current code/tests; git history was not used to claim they happened in production.</b></p>${table(["Problem","Investigation","Root cause","Fix","Learning"],debug,"dense")}${box("Story delivery", "State observable symptom → smallest evidence-gathering step → root cause → exact code-level fix → regression test. Avoid claiming production incidents you cannot prove.","good")}`);

const decisions=[
["Node.js","Network-heavy service","Java/.NET/Node","Node","Shared JS + async I/O","CPU work can block"],["Express","Small REST API","Native/Fastify/Nest","Express","Minimal middleware/routing","Less structure"],["React/Vite","Interactive SPA","Vanilla/Next/Vue","React/Vite","Component UI + fast build","Separate deployment"],["REST GitHub","Known resources","GraphQL/clone","REST","Simple/cacheable endpoints","More calls"],["Groq","Fast hosted generation","Other cloud/local","Groq","Structured model API","Vendor dependency"],["Lexical","Explainable MVP retrieval","Vector/hybrid","Weighted lexical","Deterministic/testable","Misses semantics"],["Structured output","Stable UI contract","Free text","JSON Schema","Predictable parsing","Provider schema failures"],["Post-validation","Untrusted model","Prompt only/human only","Deterministic rules","Testable safety boundary","Rules are incomplete"],["Bounded evidence","Cost/latency/relevance","Whole repo","Top evidence only","Lower noise/quota","May miss context"],["Memory cache","Single-instance MVP","Redis/database","Map + TTL","No infrastructure","Not distributed"],["Promise.all","Independent I/O","Sequential calls","Parallel","Lower latency","Need failure isolation"],["MV3 extension","In-context GitHub UX","Web only/userscript","Extension","Read/insert issue directly","DOM/permission maintenance"],["No DB","No server accounts/persistence","SQL/NoSQL","Browser history","Simple/private local history","No sync/analytics"],
];
page("15. Design decisions", table(["Choice","Requirement","Options","Selected","Reason","Trade-off"],decisions,"dense")+box("Why not send entire repo?", "It adds noise, cost, latency and attack surface. Retrieval is an engineering filter, not just a cost optimization.","good"));

page("16. Code-level walkthrough", code(`repositoriesRouter.post(
  "/:owner/:repository/analyze",
  analysisLimiter,
  async (request, response) => {
    const { owner, repository } = request.params;
    const { title, description, issueNumber } = request.body;
    // validate → retrieve → rank → generate → respond
  }
);`)+`<ul><li><code>request.params</code>: strings captured by <code>:owner</code> and <code>:repository</code>.</li><li><code>request.body</code>: JSON parsed by <code>express.json()</code>.</li><li><code>analysisLimiter</code>: middleware executes before handler and may end with 429.</li><li><code>async</code>: enables <code>await</code> and returns a Promise; <code>try/catch</code> maps errors to JSON.</li></ul>`+code(`const issues = [currentIssue, ...recentIssues, ...searchedIssues]
  .filter(Boolean)
  .filter((issue, index, items) =>
    items.findIndex(candidate => candidate.number === issue.number) === index
  );`)+`<p><code>filter(Boolean)</code> removes null current issue. The second filter keeps the first item for each issue number. Spread syntax merges arrays. Later <code>slice(0, 3)</code>/<code>slice(0, 4)</code> enforce evidence limits.</p>`);

page("17–18. JavaScript, Node & CS fundamentals", table(["Concept","RootLore connection"],[["Event loop/promises","Async fetch allows other work while I/O waits; Promise.all overlaps calls."],["Modules/collections","ES imports/exports; arrays transform/rank; Map/Set cache and deduplicate."],["Errors/HTTP/JSON","try/catch/finally maps failures; fetch serializes external contracts."],["DBMS","No server DB; add one for accounts, history, feedback, audit and jobs."],["OS","One Node process owns Map state; CPU-heavy work can block its event loop."],["Networks","DNS + HTTPS/TCP; REST/statuses; cache/parallelism/timeouts reduce latency."],["OOP","Mostly functional modules/plain objects. Closures encapsulate state; no class hierarchy."]],"dense")+box("What if await is removed?", "The variable remains a Promise; array/object consumers may fail or the response may return too early.","note"));

page("19. Limitations and roadmap", table(["Current limitation","Impact","Improvement","Trade-off"],[["Lexical-only","Misses synonym/concept matches","Hybrid BM25/embeddings + reranking","Infra/cost/opacity"],["Bounded repo understanding","Relevant unreferenced code may be missed","Index repository with freshness metadata","Storage/security/indexing work"],["Memory cache/limiter","No sharing; reset on restart","Redis + distributed locks/counters","New dependency/operations"],["Browser-local history","No cross-device sync/accounts","Auth + database","Privacy and security scope"],["4-case evaluation","Cannot claim real-world accuracy","Diverse labeled benchmark","Labeling cost"],["No Discussions/full PR diffs","Missed evidence","Add bounded connectors","More calls/context"],["Server GitHub token","Private access tied to one token","Per-user OAuth/GitHub App scopes","Auth complexity"],["Broad extension CORS","Any extension origin accepted","Exact extension ID allow-list","Environment-specific config"],["Web no timeout","Fetch may wait too long","AbortController with UX retry","Tune timeout carefully"]],"dense")+box("Prioritization", "First: broaden evaluation so you know the actual failure modes. Second: hybrid retrieval if semantic misses dominate. Third: shared cache/auth only when deployment and user needs justify their operational cost.","good"));

const q=(level,items)=>`<h2>${level}</h2>${items.map((x,i)=>`<div class="qa"><b>${i+1}. ${x[0]}</b><p><i>Tests:</i> ${x[1]} <i>Answer:</i> ${x[2]} <i>Keywords:</i> ${x[3]} <i>Follow-up:</i> ${x[4]}</p></div>`).join("")}`;
const foundation=[
["What is RootLore?","Clarity","A GitHub issue assistant grounded in bounded repository evidence with deterministic output checks.","RAG, grounding, validation","How is it unlike ChatGPT?"],["What problem?","Product sense","Scattered project knowledge, hallucinated generic advice and incomplete reports.","issues, docs, maintainers","Who benefits?"],["Main user flow?","System overview","Submit report; retrieve/rank; generate; validate; render one of four outcomes.","pipeline","Where can it fail?"],["Why RAG?","Concept","The model needs current repository-specific context not guaranteed in training.","retrieve/augment/generate","Why no vectors?"],["Interfaces?","Scope","React web SPA and Chrome MV3 extension call the same Express API.","shared backend","Why extension?"],["Four outcomes?","Correctness","Verified, inferred, possible remediation, structured issue.","confidence/provenance","How chosen?"],["Primary evidence?","Retrieval","Issues, comments, timeline, releases, docs and named files.","bounded","Why not whole repo?"],["Model?","Recall","Groq openai/gpt-oss-20b.","0.2, schema","Replaceable?"],["Database?","Honesty","None server-side; Maps cache, localStorage history and Chrome storage.","stateless MVP","When add DB?"],["Biggest strength?","Judgment","Code-enforced evidence validation after generation.","defense in depth","Is it foolproof?"],["Biggest weakness?","Honesty","Lexical and bounded retrieval can miss relevant context.","semantic recall","Improve?"],["What is grounding?","AI basic","Linking output claims to supplied evidence.","citations","Quote enough?"],["Who uses it?","Product","Reporters and maintainers in GitHub workflows.","developer UX","Private repos?"],["What is issue quality?","Feature","Six explainable checks scored in the web client.","problem, actual, OS, steps, version, logs","Can model fake score?"],["Production ready?","Maturity","Strong MVP safeguards/tests, but needs auth, distributed controls and broader eval.","trade-offs","First priority?"]];
page("20. Question bank — Level 1",q("15 foundation questions",foundation));

const impl=[
["How are issues ranked?","Code depth","Weighted shared words: title 3, labels 2, body 1, exact error 4.","15% threshold","Normalization?"],["How docs rank?","Retrieval","Paragraph chunks; term count +3 for numbers within 5%.","1200 chars","Weakness?"],["How older issues?","API","GitHub search with up to two distinctive terms, max 20.","cached","Rate limit?"],["Why filter PRs?","GitHub knowledge","Issues endpoint also returns pull requests; <code>pull_request</code> entries are removed.","normalization","GraphQL?"],["How paths found?","Safety","Regex extracts ≤3 explicit paths from allowed directory/extensions.","no scan","Missed paths?"],["Docs bounds?","Numbers","20 files, 100KB each, 750KB total.","24h cache","Selection order?"],["What is ETag?","HTTP","Validator reused with If-None-Match; 304 keeps cached data.","revalidation","TTL?"],["Cache eviction?","Implementation","At capacity delete first inserted Map key.","500/250","LRU?"],["What dedupes requests?","Concurrency","Map stores Promise by URL or analysis hash.","in-flight","Multi-process?"],["How validate quote?","Safety","Allow-listed source plus normalized exact substring ≥12 chars.","deterministic","Paraphrase?"],["How close confirms fix?","Logic","Final closer actor must author resolution-language comment; not_planned excluded.","timeline","Reporter vs maintainer?"],["How block self duplicate?","Logic","Candidate number must differ from currentIssueNumber and have duplicate claim.","allow-list","No current number?"],["How sanitize report?","Provenance","Remove unsubmitted versions/environment/actions/errors.","source facts","Title included?"],["Why schema plus parser?","Defense","Remote constraint and local regression-safe validation.","502","Recovery?"],["Failed generation recovery?","Resilience","Parse JSON object from provider error, add conservative defaults, revalidate.","no second call","Risk?"],["Rate limiter works how?","Middleware","IP Map record window; increment, headers, reject >10.","429","Memory leak/proxy?"],["CORS works how?","Web","No origin, configured origin, or extension scheme allowed; otherwise 403.","browser","Auth?"],["How UI stores history?","Frontend","Last 10 completed analyses in localStorage.","browser-local","Sensitive data?"],["Extension timeout?","Reliability","AbortController at 45 seconds.","service worker","Web timeout?"],["Optional evidence?","Resilience","Catch rejected Promise and return empty array so core pipeline continues.","degradation","Which call is core?"]];
page("20. Question bank — Level 2",q("20 implementation questions",impl));

const why=decisions.map(d=>[`Why ${d[0]}?`,`Trade-off reasoning`,`${d[4]}; accepted: ${d[5]}.`,`requirement/options/choice`,`When would you change it?`]).concat([
["Why exact quotes?","Grounding","They are mechanically verifiable against retrieved text.","provenance","Are quotes truth?"],["Why four outcomes?","UX safety","Separate direct support, inference, tentative direction and missing evidence.","calibration","How map confidence?"],["Why current issue forced in?","Correctness","Its comments may contain resolution even if ranking/search misses it.","extension context","Self-duplicate?"],["Why cache failures?","Resilience","Avoid hammering an unhealthy/rate-limited dependency for 60 seconds.","backoff","Stale error cost?"],["Why 0.2 temperature?","LLM control","Favor consistency over creativity for technical structured output.","determinism","Still nondeterministic?"],["Why local quality score?","Explainability","Simple checks should not require or trust the LLM.","deterministic","Server vs client?"],["Why no auth?","MVP scope","Public repository demo and local history avoid account infrastructure.","scope","Private data risk?"],
]);
page("20. Question bank — Level 3",q("20 WHY/design questions",why.slice(0,20)));

const scenarios=[
["GitHub is slow—what do you do?","Reliability","Use 15s timeout, cache/ETag/dedup; degrade optional sources; observe p95.","timeout, cache","Retries?"],["Groq is down?","Dependency","Return controlled 503; possible future deterministic fallback/queue.","graceful failure","Circuit breaker?"],["Two users send same report?","Concurrency","In-flight keys share work in one process; cached result reused.","coalescing","Across instances?"],["Semantic duplicate missed?","Retrieval","Inspect tokens; add synonym mapping or hybrid embeddings; measure Recall@k.","evaluation","Reranker?"],["False duplicate returned?","Safety","Require valid duplicate citation; tune ranking/threshold; add negative fixtures.","precision","Human review?"],["Repo has malicious prompt text?","Security","Treat as untrusted in system prompt and enforce local validators.","prompt injection","Tool execution?"],["Private repo requested?","Authorization","Server token decides access; current design lacks user-level authorization.","least privilege","GitHub App?"],["Multiple instances?","Scaling","Move cache/limit/lock state to Redis; add shared observability.","distributed state","Cache keys?"],["Memory grows?","Operations","Caps exist, but limiter records need cleanup; monitor and prune.","bounded cache","Eviction policy?"],["Bad JSON body?","API","Express parse error middleware returns 400 JSON.","entity.parse.failed","Body size?"],["One comment endpoint fails?","Resilience","Optional wrapper yields empty evidence; disclose reduced coverage if added.","partial failure","Silent degradation?"],["Model invents v9.2?","Validation","Version token absent from evidence causes solution removal.","allow-list","Non-version numbers?"],["Low-confidence delete advice?","Safety","Unsafe verb pattern blocks it without solution evidence.","destructive","Regex limitations?"],["Docs exceed bounds?","Performance","Priority selection and byte/file caps; only ranked passages reach prompt.","bounded context","Relevant late doc?"],["Evaluation says 100%?","Scientific thinking","Report 4/4 only; build diverse held-out set and richer metrics.","sample size","Confidence interval?"]];
page("20. Question bank — Level 4",q("15 scenario/debugging questions",scenarios));

const skeptical=[
["Isn’t this just an LLM wrapper?","Depth","No: retrieval, ranking, caching, provenance validation and outcome policy are deterministic application logic.","RAG, guardrails","Remove LLM?"],["Why trust repository comments?","Epistemics","We do not blindly trust them; source and resolution signals are shown, and inferred claims remain labeled.","provenance","Malicious content?"],["Exact quote means correct?","Nuance","No; it proves provenance only. Repository text can still be wrong.","source≠truth","Cross-check?"],["Lexical retrieval is primitive?","Trade-offs","Yes, deliberately simple for MVP explainability; limitation is documented and hybrid search is next.","MVP","Benchmarks?"],["Four tests prove nothing?","Honesty","They are regression fixtures only; README explicitly says so.","scope","Better dataset?"],["Your rate limiter is production-grade?","Honesty","No; it is process-local and depends on request.ip/proxy config.","Redis","Evasion?"],["CORS secures API?","Security","No; CORS is a browser policy, not authentication.","authn/authz","curl?"],["Why is description 10k but prompt 5k?","Code reading","Route accepts/storage response context, but provider input intentionally truncates; this may omit late details and should be surfaced/improved.","bounds","Fix?"],["Can validators catch all hallucinations?","Honesty","No; they catch defined classes. Semantic misinterpretation can remain.","defense in depth","Evals?"],["Why no retry?","Reliability","Retries risk amplifying quota/thundering herd; add bounded backoff only for retryable statuses.","idempotency","Circuit breaker?"],["Why SHA-256?","Implementation","Stable compact cache identity; not a security claim.","hash","Collision?"],["Could cache leak private data?","Security","Yes, server-process cache is not user-partitioned; per-user authorization/cache scoping is needed.","tenant isolation","Encryption?"],["Why client quality score?","Architecture","It is immediate and deterministic, but shared server logic would prevent drift across clients.","duplication","Extension parity?"],["Why broad extension origins?","Challenge","Convenience for unpacked extension IDs; production should exact-allow-list known ID.","CORS","Config?"],["What did you personally build?","Integrity","Answer only your actual contribution; distinguish repository facts from personal authorship.","ownership","Hardest part?"]];
page("20. Question bank — Level 5",q("15 skeptical interviewer questions",skeptical));

const chains=[
["“Just an LLM wrapper.”","The differentiator is deterministic retrieval, ranking, caching and post-validation.","“Then why LLM?”","For synthesis and structured rewriting; deterministic pieces still work without it."],
["“Why not embeddings?”","Explainable MVP and measurable behavior.","“So recall is weak?”","Potentially; I would prove the gap on a held-out dataset, then add hybrid retrieval."],
["“Can you guarantee no hallucination?”","No. We reduce defined failure classes.","“What remains?”","Semantic misreading, incorrect repository text and validators’ blind spots."],
["“Closed issue means solved?”","No; closure can be stale/duplicate/declined.","“Your rule?”","Exclude not_planned and require the closer’s explicit resolution comment."],
["“Why Promise.all?”","Independent I/O overlaps to reduce latency.","“One fails?”","Optional wrappers resolve empty; core unwrapped failures propagate."],
["“Why Redis?”","Not required for one-process MVP.","“When required?”","Multiple instances, durable shared limits, higher cache hit rate and cross-process locks."],
["“CORS is security?”","Only a browser-origin control.","“What secures API?”","Authentication, authorization, quotas and validation."],
["“100% accuracy?”","Only 4/4 toy top-1 retrieval fixtures.","“Credible claim?”","Dataset size + Precision@1/Recall@5/MRR/groundedness and latency."],
["“Why JSON Schema?”","Stable contract and less ambiguous parsing.","“Enough?”","No; local shape, quote, version and outcome validation remain essential."],
["“Send the whole repo.”","It increases noise, cost, latency and attack surface.","“But you may miss files.”","Yes; explicit-path retrieval is a precision/coverage trade-off; indexing can improve recall."],
["“Private repos?”","Backend token permissions control GitHub access.","“Safe multi-user?”","Not yet; needs per-user OAuth/GitHub App and tenant-scoped caching."],
["“Model says delete cache.”","Low-confidence destructive verbs are blocked without solution evidence.","“Regex foolproof?”","No; expand policy/testing and consider structured action classification."],
["“GitHub limit exceeded.”","Core fetch returns status/message; cached fresh data avoids many calls.","“Improve?”","Backoff, stale-if-error, metrics and authenticated/app tokens."],
["“Why extension?”","It reads/inserts the issue in context.","“Risk?”","GitHub DOM changes, permissions and exact-origin/API host management."],
["“No database—backend project?”","Backend value is orchestration, policies, caches and external integrations.","“Add DB for what?”","Accounts, shared history, feedback, audit/evaluation and jobs."],
];
page("21. Cross-questioning chains I",chains.slice(0,8).map((c,i)=>`<div class="chain"><b>${i+1}. Interviewer:</b> ${c[0]} <b>Candidate:</b> ${c[1]}<br><b>Interviewer:</b> ${c[2]} <b>Candidate:</b> ${c[3]}</div>`).join(""));
page("21. Cross-questioning chains II",chains.slice(8).map((c,i)=>`<div class="chain"><b>${i+9}. Interviewer:</b> ${c[0]} <b>Candidate:</b> ${c[1]}<br><b>Interviewer:</b> ${c[2]} <b>Candidate:</b> ${c[3]}<br><span class="muted">Next push: quantify the trade-off, name the current bound, then propose one measured improvement.</span></div>`).join(""));

page("ROOTLORE 15-MINUTE REVISION", `<p><b>Definition:</b> Evidence-grounded GitHub issue assistant that retrieves, ranks, generates and validates.</p><p><b>Problem:</b> scattered repo knowledge + incomplete reports + LLM hallucination.</p><div class="diagram compact">Web/Extension → Express → GitHub evidence → lexical rank → ≤3 enriched issues + ≤4 passages → Groq schema → deterministic checks → 4 outcomes → UI</div><p><b>Stack:</b> JavaScript ES modules, Node, Express, React/Vite, MV3, GitHub REST, Groq gpt-oss-20b, JSON Schema, cors, dotenv, Node tests.</p><p><b>Top decisions:</b> bounded evidence; explainable lexical scoring; structured output; post-validation; in-memory MVP cache.</p><p><b>Hard questions:</b> not merely wrapper; no guarantee of zero hallucination; no embeddings due MVP trade-off; 4/4 is tiny regression only; multi-instance requires shared state.</p><p><b>Limitations:</b> semantic misses, bounded code view, local caches/limiter, local history/no auth, tiny eval.</p><p><b>Key numbers:</b> issues 100+search 20; selected 3; comments 20; timeline 100; releases 10/3 sent; docs 20/750KB/100KB; source 3/150KB; passages 4; score threshold 15%; number proximity 5%; GitHub/Groq/extension timeouts 15/30/45s; caches 15m/6h/24h; analysis 24h; rate 10/10m; title 200; description 10k (5k sent); output 2200.</p>${box("60-second pitch", "RootLore solves GitHub issues using repository evidence rather than generic model memory. A React app or Chrome extension sends a report to Express. The backend retrieves recent and searched issues plus bounded comments, timelines, releases, docs and explicitly referenced files. It ranks them lexically, sends only the strongest context to Groq using strict structured output, then validates issue numbers, exact quotes, versions, duplicate claims and risky actions. It returns a verified solution, labeled inference, tentative remediation or structured issue. The main trade-off is explainable simplicity versus semantic recall; hybrid retrieval and distributed state are logical next steps.","good")}`);

const rapid=[
["RAG?","Retrieve context, augment prompt, generate answer."],["Model?","openai/gpt-oss-20b through Groq."],["Temperature?","0.2 for consistency."],["Issue ranking?","Title×3, labels×2, body×1, exact error×4."],["Threshold?","15% issue relevance."],["Recent issues?","Up to 100, one page."],["Search results?","Up to 20."],["Enriched issues?","At most 3."],["Prompt passages?","At most 4."],["Named files?","At most 3, explicit only."],["Docs cap?","20 files, 750KB total, 100KB each."],["Timeouts?","GitHub 15s, Groq 30s, extension 45s."],["Rate limit?","10 analyses per IP per 10 minutes."],["Cache TTLs?","Issues 15m, support 6h, docs 24h, Groq 24h."],["ETag?","Conditional stale-cache revalidation."],["In-flight dedup?","Concurrent identical work shares a Promise."],["Why POST?","Report body triggers composed analysis."],["Why 502?","Invalid provider structure."],["Why 503?","Unavailable/misconfigured upstream."],["DB?","No server DB; localStorage and Chrome storage only."],["Vectors?","Not used; retrieval is lexical."],["Duplicate safety?","Allowed issue + duplicate claim + not current issue."],["Quote safety?","Exact normalized substring, minimum 12 chars."],["Closure safety?","Closer-confirmed resolution; not_planned excluded."],["Version safety?","No unseen version in suggested solution."],["Unsafe action?","Low-confidence destructive actions removed."],["Four outcomes?","Verified, inferred, possible, structured issue."],["Tests?","44 passing locally."],["Evaluation?","4/4 toy top-1 regression only."],["First scale fix?","Shared cache/limiter/locks plus observability."]];
page("ROOTLORE RAPID FIRE",table(["Question","1–2 sentence answer"],rapid,"rapid"));

page("48-hour study plan & truth checklist", `<h2>Day 1 — understand</h2><ol><li>Draw the pipeline from memory twice.</li><li>Read the route, then <code>analysis.js</code>, <code>github.js</code>, <code>groq.js</code>.</li><li>Explain every bound and outcome aloud.</li><li>Practice the 15/30/60/120-second pitches.</li></ol><h2>Day 2 — defend</h2><ol><li>Answer Level 3–5 without notes.</li><li>Run five cross-question chains aloud.</li><li>Explain two code snippets line-by-line.</li><li>Rehearse one hypothetical debugging story and label it honestly.</li><li>Finish with the 15-minute revision and rapid fire.</li></ol>${box("Truth checklist", "Say <b>source-verified</b>, not production-proven. Say <b>4/4 regression fixtures</b>, not 100% accurate. Say <b>reduces hallucinations</b>, not eliminates them. Say <b>bounded repository evidence</b>, not entire repo. Say <b>functional/modules</b>, not class-heavy OOP. Never claim personal authorship of a component unless it is true.","bad")}<p class="small"><b>Verification performed:</b> <code>npm test</code> → 44/44; <code>npm run evaluate</code> → 4/4; <code>npm --prefix web run build</code> → success. README and code are consistent on these current baselines. Resume representation remains unverified because no resume file was supplied.</p>`);

const css=`@page{size:A4;margin:0}*{box-sizing:border-box}body{margin:0;background:#dbe3ea;color:#172332;font-family:Segoe UI,Arial,sans-serif}.page{width:210mm;height:297mm;padding:13mm 14mm 12mm;background:#fff;position:relative;page-break-after:always;overflow:hidden}header{display:flex;justify-content:space-between;border-bottom:1px solid #cad5df;padding-bottom:3mm;color:#587086;font-size:8pt;letter-spacing:.08em}footer{position:absolute;bottom:5mm;left:14mm;right:14mm;color:#8192a2;font-size:7pt;border-top:1px solid #e0e6eb;padding-top:2mm}h1{font-size:22pt;margin:7mm 0 4mm;color:#0d3b57}h2{font-size:12pt;margin:4mm 0 1.5mm;color:#176787}p,li,td,th{font-size:8.6pt;line-height:1.35}p{margin:1.5mm 0}ul,ol{margin:1.5mm 0 2mm;padding-left:5mm}li{margin:.8mm 0}code{font-family:Consolas,monospace;color:#7a285f}pre{background:#102432;color:#eef7fb;padding:3mm;border-radius:2mm;white-space:pre-wrap;margin:2mm 0}pre code{color:#eef7fb;font-size:7.5pt;line-height:1.3}.cover{padding-top:20mm}.cover h2{font-size:27pt;max-width:150mm;color:#176787}.lede{font-size:14pt;max-width:160mm}.eyebrow{color:#b34b72;font-weight:700;letter-spacing:.14em}.box{border-left:4px solid #3785a4;background:#edf6fa;padding:2.5mm 3mm;margin:3mm 0;font-size:8.5pt}.box b{display:block;margin-bottom:1mm}.good{border-color:#28906c;background:#eef9f5}.warn{border-color:#d99b27;background:#fff8e8}.bad{border-color:#c7444c;background:#fff0f1}.facts{display:grid;grid-template-columns:repeat(4,1fr);gap:2mm;margin:5mm 0}.facts b{font-size:18pt;color:#176787}.facts span{font-size:8pt;color:#607485}.flow{display:flex;align-items:center;gap:2mm;margin:4mm 0}.flow span{padding:2mm 3mm;background:#e9f4f8;border-radius:2mm;font-weight:700}.flow.big{font-size:12pt;margin:12mm 0}.diagram{padding:7mm;text-align:center;background:#102f42;color:white;border-radius:3mm;font-size:12pt;line-height:1.75;margin:5mm 0}.diagram.compact{font-size:9pt;padding:4mm}.three{display:grid;grid-template-columns:repeat(3,1fr);gap:3mm}.three div{background:#eef6f8;padding:4mm;border-radius:2mm}table{width:100%;border-collapse:collapse;margin:2mm 0 3mm;table-layout:fixed}th{background:#174c66;color:white;text-align:left}th,td{border:1px solid #cfd9e1;padding:1.6mm;vertical-align:top}.dense th,.dense td{font-size:7.25pt;line-height:1.22;padding:1.2mm}.rapid th,.rapid td{font-size:7pt;padding:.8mm}.steps li{margin:1.8mm 0}.qa{border-bottom:1px solid #d8e0e6;padding:1.1mm 0}.qa>b{font-size:8.2pt;color:#174c66}.qa p{font-size:7.2pt;margin:.5mm 0}.qa i{font-style:normal;font-weight:700;color:#9a3f69}.chain{font-size:8pt;line-height:1.4;padding:2mm;margin:1.5mm 0;background:#f2f6f8;border-radius:2mm}.chain b{color:#176787}.muted{color:#6b7d8b}.small{font-size:7.5pt}`;
const html=`<!doctype html><html><head><meta charset="utf-8"><title>RootLore Interview Guide</title><style>${css}</style></head><body>${pages.join("")}</body></html>`;
const out=resolve("report/RootLore_Interview_Guide.html");
writeFileSync(out,html,"utf8");
console.log(`Wrote ${out} with ${pages.length} pages`);
